import { supabase } from './supabase.js';
export const subjects = [
 { name:'Physics', short:'PH', color:'lilac', chapters:['Physics & Measurement','Kinematics','Laws of Motion','Work, Energy & Power','Rotational Motion','Gravitation','Properties of Solids & Liquids','Thermodynamics','Kinetic Theory of Gases','Oscillations & Waves','Electrostatics','Current Electricity','Magnetic Effects of Current & Magnetism','Electromagnetic Induction & AC','Electromagnetic Waves','Optics','Dual Nature of Matter','Atoms & Nuclei','Electronic Devices','Experimental Skills'] },
 { name:'Organic Chemistry', short:'OC', color:'peach', chapters:['Basic Principles of Organic Chemistry','Hydrocarbons','Haloalkanes & Haloarenes','Alcohols, Phenols & Ethers','Aldehydes, Ketones & Carboxylic Acids','Organic Compounds Containing Nitrogen','Biomolecules','Principles Related to Practical Chemistry'] },
 { name:'Physical Chemistry', short:'PC', color:'blue', chapters:['Some Basic Concepts of Chemistry','Atomic Structure','Chemical Bonding & Molecular Structure','Chemical Thermodynamics','Solutions','Equilibrium','Redox Reactions & Electrochemistry','Chemical Kinetics'] },
 { name:'Inorganic Chemistry', short:'IOC', color:'sage', chapters:['Classification of Elements & Periodicity','p-Block Elements','d- and f-Block Elements','Coordination Compounds'] },
 { name:'Zoology', short:'ZO', color:'rose', chapters:['Animal Kingdom','Structural Organisation in Animals','Biomolecules','Cell: Structure & Function','Human Physiology','Reproduction','Evolution','Human Health & Disease'] },
 { name:'Botany', short:'BO', color:'green', chapters:['Diversity in Living World','Plant Kingdom','Morphology of Flowering Plants','Anatomy of Flowering Plants','Cell: Structure & Function','Plant Physiology','Sexual Reproduction in Flowering Plants','Genetics & Evolution','Biology & Human Welfare','Biotechnology','Ecology & Environment'] },
];
export const todayKey=(d=new Date())=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
export async function loadAll(userId){
 const [p,c,t,s]=await Promise.all([supabase.from('profiles').select('*').eq('id',userId).maybeSingle(),supabase.from('chapters').select('*').eq('user_id',userId),supabase.from('tasks').select('*').eq('user_id',userId).order('due_date',{ascending:true,nullsFirst:false}),supabase.from('study_sessions').select('*').eq('user_id',userId).order('started_at',{ascending:false})]);
 for(const r of [p,c,t,s])if(r.error)throw r.error;
 return {profile:p.data,chapters:c.data??[],tasks:t.data??[],sessions:s.data??[]};
}
export async function ensureChapters(userId,saved){const have=new Set(saved.map(c=>`${c.subject}|${c.name}`));const missing=subjects.flatMap(s=>s.chapters.filter(n=>!have.has(`${s.name}|${n}`)).map(name=>({user_id:userId,subject:s.name,name,status:'not_started',progress:0})));if(!missing.length)return saved;const {data,error}=await supabase.from('chapters').insert(missing).select();if(error)throw error;return [...saved,...data]}
export function statsFrom(d){const today=todayKey(),daily=new Map();for(const s of d.sessions)if(s.completed)daily.set(s.study_date,(daily.get(s.study_date)||0)+Number(s.duration_minutes||0));const cursor=new Date(`${today}T12:00:00`);if(!daily.has(today))cursor.setDate(cursor.getDate()-1);let streak=0;while(daily.has(todayKey(cursor))){streak++;cursor.setDate(cursor.getDate()-1)}let longest=0,run=0,previous=null;for(const day of [...daily.keys()].sort()){const date=new Date(`${day}T12:00:00`);run=previous&&(date-previous)/86400000===1?run+1:1;longest=Math.max(longest,run);previous=date}const subjectProgress=subjects.map(s=>{const chapters=d.chapters.filter(c=>c.subject===s.name),percent=chapters.length?Math.round(chapters.reduce((n,c)=>n+Number(c.progress||0),0)/chapters.length):0;return{...s,chapters,percent,completed:chapters.filter(c=>c.status==='completed').length}});const week=Array.from({length:7},(_,i)=>{const date=new Date();date.setDate(date.getDate()-(6-i));const key=todayKey(date);return{key,label:date.toLocaleDateString('en',{weekday:'short'}),minutes:daily.get(key)||0}});return{today,daily,streak,longest,done:d.tasks.filter(t=>t.completed).length,minutes:d.sessions.filter(s=>s.completed).reduce((n,s)=>n+Number(s.duration_minutes||0),0),todayMinutes:daily.get(today)||0,subjectsProgress:subjectProgress,overall:Math.round(subjectProgress.reduce((n,s)=>n+s.percent,0)/6),completedChapters:d.chapters.filter(c=>c.status==='completed').length,week}}
